### PR TITLE
Bump Spin shim to Spin v2.1.0

### PR DESCRIPTION
**Pull request by radu-matei**
depends on https://github.com/fermyon/spin-trigger-sqs/pull/13

This commit updates the Spin dependency to v2.1.0.

### CODE REVIEW

**Comment by radu-matei** [comment]
Not sure why the Lunatic shim build failure, this PR does not change anything about that shim.

**Comment by Mossaka** [comment]
I will take a look at the lunatic shim failure

**Comment by Mossaka** [comment]
The CI was fixed. @radu-matei

**Review by Mossaka — APPROVED** [review]
lgtm

**Pull request merged**
