### PR TITLE
feat: add default executor to spin shim

### PR DESCRIPTION
**Pull request by Mossaka**
This PR mostly follows https://github.com/containerd/runwasi/pull/156 to add a default executor alongside with the spin executor. It enables a pod to run both linux containers and spin applications. 

TODO:
- [ ] add integration tests
- [ ] add a Dapr demo that spin application is calling into
- [x] fix the CI to emit build artifacts and reuse these artifacts for integration tests

### CODE REVIEW

**Comment by 0xE282B0** [comment]
Hi @Mossaka,
Can I support you with a Spin/Dapr demo or are you already working on that?

**Comment by thangchung** [comment]
+1 for @0xE282B0's idea. I'm waiting to have a demo on Spin/Dapr as well.

**Comment by Mossaka** [comment]
@0xE282B0 thanks for bringing it up. It's in my todo list to build a demo for spin + dapr. I would hugely appreciate your help on this!

**Comment by Mossaka** [comment]
Note: the CI failed because it ran into the disk pressure issue. I will be working on emitting artifacts from build and then ran integration tests.

**Comment by Mossaka** [comment]
I am running into this problem from the containerd log:

```
[ERROR] executable "/" does not have the correct permission set
[ERROR] failed to initialize container process: invalid executable: /
```

**Comment by Mossaka** [comment]
I think the issue was the libcontainer requires the entrypoint to be an executable, which we tried to push off. See https://github.com/containers/youki/issues/2220. 

In the meantime, you probably want to do something like the spin shim is doing described in the https://github.com/deislabs/containerd-wasm-shims/issues/120.

**Comment by Mossaka** [comment]
Merging it now. I will make an issue for each TODO item listed in this PR's description.

**Pull request merged**
