### PR TITLE
feat: add spin-dapr example

### LINKED ISSUE #130: spin + dapr demo
#121 adds the default executor to the spin shim to allow it run with Linux containers side-by-side in a pod. Now we need to add a demo for Spin + Dapr integration. 

@0xE282B0 are you interested in taking this issue?

### PR DESCRIPTION
**Pull request by 0xE282B0**
This PR adds a simple demo of how a spin application can be triggered by dapr to demonstrate the default executor feature.

Closes #130

### CODE REVIEW

**Review by Mossaka — APPROVED** [review]
I didn't run it locally today but the changes LGTM. 

I will try to run it tomorrow

**Comment by Mossaka** [comment]
Need a rebase

**Comment by Mossaka** [comment]
For some reason I could not get this example working with `v0.9.0` k3d cluster

**Comment by 0xE282B0** [comment]
Just saw this lying around, rebased and updated example readme for use with k3d and `0.10.0`.

**Review by Mossaka — APPROVED** [review]

**Comment by Mossaka** [comment]
Can you add some integration tests for this image?

**Review by Mossaka — APPROVED** [review]

**Pull request merged**
