### PR TITLE
ci: pin cross and rust versions

### PR DESCRIPTION
**Pull request by Mossaka**
This pull request includes updates to the Rust toolchain and the Makefile to ensure specific versions are used and to include new components and targets. The most important changes include updating the `rust-toolchain.toml` file to use Rust version 1.75.0 and updating the `install-cross` target in the `Makefile` to specify a specific commit when installing `cross`.

### CODE REVIEW

**Comment by Mossaka** [comment]
Confirmed that an older cross image `ghcr.io/cross-rs/x86_64-unknown-linux-musl:main@sha256:a8a5f982bca1a7c91227bb342749282a2eebc93daef16ce0` works. The newer image introduces the PIE build issue.

**Comment by Mossaka** [comment]
It looks like the `enable-default-pie` flag was removed in this [PR](https://github.com/cross-rs/cross/pull/1346).

**Comment by Mossaka** [comment]
https://github.com/cross-rs/cross/pull/1418 this PR adds PIE back.

**Review by devigned — APPROVED** [review]
Nice work locking in the version to avoid the PIE compilation issue.

**Comment by Mossaka** [comment]
> Nice work locking in the version to avoid the PIE compilation issue.

Thanks! Just to clarify, locking in the version did not fix the PIE compilation issue. The fix was on upstream cross repo to enable PIE compilation in musl library.

**Pull request merged**
