### PR TITLE
Chore: bump version to v0.4.0

### PR DESCRIPTION
**Pull request by Mossaka**
@devigned Do we want to follow the runtimeclass and shim binary versioning scheme described in https://github.com/deislabs/containerd-wasm-shims/pull/16?

### CODE REVIEW

**Comment by devigned** [comment]
> @devigned Do we want to follow the runtimeclass and shim binary versioning scheme described in #16?

Remind me. Did we determine that existing workloads will not run with the latest versions of the shims?

**Comment by devigned** [comment]
Also reminds me to get the #16 updated and merged. I'll do that today.

**Comment by Mossaka** [comment]
> > @devigned Do we want to follow the runtimeclass and shim binary versioning scheme described in #16?
> 
> Remind me. Did we determine that existing workloads will not run with the latest versions of the shims?

I believe the existing slight workloads will not run with the v0.4.0 slight shim. The reason for that is we renamed `http` to `http-server` to accomondate the addition of `htto-client` capability.

**Review by devigned — APPROVED** [review]
lgtm

**Pull request merged**
