### PR TITLE
refactor: re-implement the slight shim with libcontainer instance

### PR DESCRIPTION
**Pull request by Mossaka**
This commit re-implements the `slight` shim with `LibcontainerInstance` trait. This follows #121

### CODE REVIEW

**Comment by Mossaka** [comment]
I've updated this PR to include a few other things
1. split python setup script to bash scripts for better configurations. 
2. the CI uses built artifacts for integration tests, instead of building its own binaries.

**Comment by Mossaka** [comment]
Woohoo!! The integration test is passed!

**Comment by Mossaka** [comment]
Going to merge this in now.

**Comment by Mossaka** [comment]
Could you please take a look? @devigned @0xE282B0 @jprendes

**Comment by 0xE282B0** [comment]
Yay, looks good!
Is there a reason that all shims are built together?
When more shims are added we may run into the same problem.

If it is ok to build the shims in parallel, it could look like this:
https://github.com/Mossaka/shims/pull/1
https://github.com/0xE282B0/containerd-wasm-shims/actions/runs/5935591013

**Comment by Mossaka** [comment]
> If it is ok to build the shims in parallel, it could look like this:

I created an issue #126 to discuss ways to make the CI faster. Building the shims in parallel is a great idea! Would you like to create a PR for this repo?

**Comment by Mossaka** [comment]
Merging it in now

**Pull request merged**
