### PR TITLE
Bump the Spin Version

### PR DESCRIPTION
**Pull request by stevesloka**
Bumps the spin version to v1.4.0.

### CODE REVIEW

**Review by Mossaka — APPROVED** [review]
thank you! you beat me to it. 

It's so awesome to see a version bump only needs to change the version tag!

**Comment by Mossaka** [comment]
I believe you will need to bump wasmtime to 10

**Comment by Mossaka** [comment]
Could you please sign the CLA? @stevesloka

**Comment by stevesloka** [comment]
@microsoft-github-policy-service agree company="Outerbase"

**Comment by stevesloka** [comment]
@Mossaka I has to force push to rebase and sign the commit. I also commented on the CLA, so hopefully that all works. 🤞

**Comment by Mossaka** [comment]
Thank you! Once CI passes I will merge it in.

**Comment by Mossaka** [comment]
Oh it looks like the commits are not signed yet. @stevesloka

**Comment by stevesloka** [comment]
@Mossaka ok sorry about that, I got all the signing fixed up now. Thanks!

**Pull request merged**
