### PR TITLE
fix: show logs of spin module

### LINKED ISSUE #123: No print output from within Spin app
Hi,
While testing the shims on the `main` branch I found that I can't see print from within the HTTP handler anymore.

Simple example:
```Rust
use anyhow::Result;
use spin_sdk::{
    http::{Request, Response},
    http_component,
};

/// A simple Spin HTTP component.
#[http_component]
fn handle_hello_http(req: Request) -> Result<Response> {
    // #### This does not appear in log ####
    println!("{:?}", req.headers());
    // #############################
    Ok(http::Response::builder()
        .status(200)
        .header("foo", "bar")
        .body(Some("Hello, Fermyon".into()))?)
}
```

With [v0.8.0](https://github.com/deislabs/containerd-wasm-shims/releases/tag/v0.8.0) I can see the headers printed to the container log on every request. When using the shim from `main` there is no output. @Mossaka I guess it is related to the LibContainer change.

Btw. It's awesome that we have a Redis trigger now 😊

### PR DESCRIPTION
**Pull request by 0xE282B0**
Add trigger-hook to forward spin module stdout.

@jpflueger, @voigt could you check if it fixes the problem for you as well?
closes #123

### CODE REVIEW

**Comment by voigt** [comment]
Will look into it asap.

**Review by Mossaka — APPROVED** [review]
lgtm!

**Comment by Mossaka** [comment]
It looks like the tests are failing. Trying it again...

**Comment by jprendes** [comment]
I fail to see how `StdioTriggerHook` is used.
I don't see it being constructed anywhere.

@0xE282B0 is there any commit missing here?

**Comment by 0xE282B0** [comment]
@jprendes 🤣 It seems that you are the firs one who is taking a closer look.

**Pull request merged**
