### PR TITLE
Handle SIGINT too on killing

### PR DESCRIPTION
**Pull request by rumpl**
This makes ctrl+c work when running this shim with Docker

### CODE REVIEW

**Comment by squillace** [comment]
@devigned can you have a look at this with @rumpl ?

**Review by Mossaka — APPROVED** [review]
lgtm!

**Review by danbugs — APPROVED** [review]
LGTM

**Comment by Mossaka** [comment]
@rumpl could you please sign off your commits?

**Review by devigned — APPROVED** [review]
lgtm! Thank you

**Comment by devigned** [comment]
> @rumpl could you please sign off your commits?

I believe the commit is signed.

**Comment by squillace** [comment]
huh, what does THAT mean......?   https://github.com/deislabs/containerd-wasm-shims/actions/runs/4073348292/jobs/7028521089#step:5:944

**Pull request merged**
